# numpy = for mathematical operation like arrays , matrices , fourier transform etc.

In [1]:
import numpy as np

In [2]:
np.array([2,4,56,422,32,1]) # 1D array

array([  2,   4,  56, 422,  32,   1])

In [3]:
a = np.array([2,4,56,422,32,1]) # vector

In [4]:
a

array([  2,   4,  56, 422,  32,   1])

In [5]:
type(a)

numpy.ndarray

## 2d array (matrix)

In [10]:
b = np.array([[1,3,4],[2,6.7,76]])
print(b)

[[ 1.   3.   4. ]
 [ 2.   6.7 76. ]]


## 3d array (tensor)

In [14]:
c = np.array([[1,3,5,9],[0.3,2,4.5,6],[1,2,3,3],[2,2,2,2]])
print(c)

[[1.  3.  5.  9. ]
 [0.3 2.  4.5 6. ]
 [1.  2.  3.  3. ]
 [2.  2.  2.  2. ]]


# dtype ----> data type

In [17]:
np.array([[1,2,3],[4,5,6]] , dtype = complex)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [19]:
np.array([0,1,0,3,4,5] , dtype=bool)

array([False,  True, False,  True,  True,  True])

# arange and reshape

In [2]:
# arange(start,end,step)

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
np.arange(1,11).reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

# zeros , ones and random --->>> use inside the tuple

In [38]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.random.random(4)

array([0.73385447, 0.66131986, 0.39516952, 0.19844787])

In [36]:
np.random.random((4,2))

array([[0.93193011, 0.91596012],
       [0.98732709, 0.29820267],
       [0.89321353, 0.61705976],
       [0.84166746, 0.91537124]])

In [9]:
np.random.rand(4) # [0,1)

array([0.0438247 , 0.34433016, 0.43912557, 0.76501052])

In [5]:
np.random.rand(4,2)

array([[0.01852837, 0.18979311],
       [0.05703191, 0.70195696],
       [0.26242192, 0.67108474],
       [0.05127912, 0.18202051]])

In [6]:
np.random.randn(4,2) # n = normal distribution value 

array([[-1.33191089, -0.90415454],
       [-0.54587086,  0.85139087],
       [ 0.57288522, -0.60040763],
       [-0.1185364 ,  1.58980471]])

In [9]:
np.random.randint(187)

20

In [10]:
np.random.randint(234,244)

240

In [14]:
np.random.randint(234,256,5) #low value,high value,size

array([249, 253, 238, 238, 249])

# linspace -->> linear sequence

In [4]:
np.linspace(1,3,6) # Return evenly spaced numbers over a specified interval.


array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [41]:
# identity 

In [42]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# array operation 

In [16]:
z1 = np.arange(12).reshape(3,4)
z2 = np.arange(12,24).reshape(3,4)


In [46]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
z1+3

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [49]:
z2-10

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [50]:
z1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [51]:
z1**3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [52]:
z2%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [53]:
z1*z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [54]:
z1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
np.max(z1)

11

In [56]:
np.min(z2)

12

In [57]:
np.sum(z1)

66

In [60]:
np.product(z2)

816826368

In [61]:
np.mean(z1)

5.5

In [62]:
np.std(z1)

3.452052529534663

In [64]:
np.var(z2)

11.916666666666666

In [65]:
np.sin(z2)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [67]:
np.log(z2)

array([[2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422]])

In [68]:
np.exp(z2)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

# *ravel ---> converting any dimension to 1d*

In [74]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
np.ravel(z1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
z2.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

# **stacking ---> joining of arrays**

## **stacking**   =====  *hstack* &  *vstack* 

In [17]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
np.hstack((z1,z2)) # horizental stack used inside the tuple

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [83]:
np.vstack((z1,z2)) # vertical stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# splitting --> opposite of stacking 

## hsplit & vsplit 

In [84]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
np.hsplit(z1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [88]:
np.hsplit(z1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [89]:
np.vsplit(z1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

# indexing and slicing 

In [2]:
import numpy as np

In [3]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [4]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
p1[0]

0

In [6]:
p1[-6]

4

In [ ]:
# 2d

In [7]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# fetching element 6

p2[1,2] # 1st row 2nd column

6

In [35]:
p2[1][2]

6

In [11]:
# fetching element 11

p2[2,3]

11

In [36]:
p2[2][3]

11

In [12]:
# 3d 

In [13]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
# fetch element 5

p3[1,0,1]

5

In [15]:
# fetch element 2 

p3[0,1,0]
   

2

In [16]:
# fetch element 0

p3[0,0,0]

0

# slicing

In [17]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# fetch 2,3,4

p1[2:5]

array([2, 3, 4])

In [19]:
# 2d 

In [20]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# fetch 1st row

p2[0,0:4]

array([0, 1, 2, 3])

In [23]:
p2[0,:]

array([0, 1, 2, 3])

In [26]:
# fetch 3rd column

p2[0:3,2]

array([ 2,  6, 10])

In [27]:
p2[:,2]

array([ 2,  6, 10])

In [37]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
p2[:2,2:]

array([[2, 3],
       [6, 7]])

In [41]:
x=np.arange(20)

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
x[0:5]=50

In [44]:
x

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
x>40

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [23]:
arr1=np.random.randint(1,10,4)
arr2=np.random.randint(10,20,4)

In [24]:
arr1

array([6, 7, 8, 2])

In [25]:
arr2

array([11, 17, 19, 18])

In [28]:
np.concatenate((arr1,arr2))

array([ 6,  7,  8,  2, 11, 17, 19, 18])

In [30]:
np.clip(arr1,1,5)

array([5, 5, 5, 2])